name: "Custom Deploy"
description: "Deploy Node.js app"

inputs:
  environment:
    required: true
  version:
    required: true
  notify-team:
    default: "false"

outputs:
  deployment-url:
    description: "URL of deployment"
  deployment-time:
    description: "Deployment duration"

runs:
  using: "composite"
  steps:
    - shell: pwsh
      run: |
        Write-Host "Deploying version ${{ inputs.version }} to ${{ inputs.environment }}"
        $start = Get-Date
        Start-Sleep -Seconds 3
        $end = Get-Date
        $duration = [math]::Round(($end - $start).TotalSeconds)

        # fallback path if GITHUB_OUTPUT is not set
        $outputFile = $env:GITHUB_OUTPUT
        if ([string]::IsNullOrEmpty($outputFile)) {
          $outputFile = "$env:RUNNER_TEMP\github_output.txt"
        }

        "deployment-url=https://app.${{ inputs.environment }}.example.com" >> $outputFile
        "deployment-time=$duration" >> $outputFile

        if ("${{ inputs.notify-team }}" -eq "true") {
          Write-Host "Team has been notified."
        }
